#!/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

COMMIT_MSG="$1"

if [ -z "$COMMIT_MSG" ]; then
    echo -e "\e[31mERROR: Commit aborted. Missing argument in prepare-commit-msg.\e[0m"
    exit 1
else
    if [ ! -z "$(cat $COMMIT_MSG)" ]; then
        exit 0
    fi

    REGEX="([A-Z]+-[0-9]+)"
    BRANCH="$(/usr/bin/git branch --show-current)"

    if [[ $BRANCH =~ $REGEX ]]; then
        echo "[${BASH_REMATCH[1]}] " > "$COMMIT_MSG"
    fi
fi