[project]
profile = ubuntu

[ubuntu]
image = ubuntu:latest

[alias:apt-update]
desc = Update package lists.
cmd = apt-get update

[alias:install-curl]
desc = Install curl.
cmd = apt-get install -y curl
hidden = true

[alias:install-copilot]
desc = Install Github Copilot CLI.
cmd = curl -fsSL https://gh.io/copilot-install | bash
hidden = true

[alias:deps]
desc = Install dependencies.
pipeline = apt-update,install-curl,install-copilot

[alias:copilot]
desc = Run Github Copilot CLI.
cmd = copilot
interactive = true

[alias:shell]
desc = Run bash shell.
cmd = /bin/bash
interactive = true

[alias:setup]
desc = Run setup.sh script.
cmd = ./Unix/setup.sh --debug --noconfirm --skip=docker --skip=alacritty

[arch]
image = archlinux:latest

[alias:shell]
desc = Run bash shell.
cmd = /bin/bash
interactive = true

[alias:setup]
desc = Run setup.sh script.
cmd = ./Unix/setup.sh --debug --noconfirm --skip=docker --skip=alacritty
