[project]
profile = ubuntu

[ubuntu]
image = ubuntu:latest

[alias:shell]
cmd = /bin/bash
interactive = true

[alias:setup]
cmd = ./Unix/setup.sh --debug --noconfirm --skip=docker --skip=alacritty

[arch]
image = archlinux:latest

[alias:shell]
cmd = /bin/bash
interactive = true

[alias:setup]
cmd = ./Unix/setup.sh --debug --noconfirm --skip=docker --skip=alacritty
