#! /bin/sh

# Set configuration
bspc config border_width              1
bspc config window_gap                2
bspc config split_ratio            0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer  true

# Border
bspc config focused_border_color "#8f7c56"
bspc config normal_border_color  "#073642"
bspc config active_border_color  "#073642"

# Assign application to workspaces
bspc rule -a keepassxc desktop='3'

#################################################################################
#                                 Autostart                                     #
#################################################################################

# Start sxhkd for keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Assign workspaces to displays (spread 10 desktops over all monitors)
set -- $(bspc query -M --names)
n=$#
if [ "$n" -gt 0 ]; then
    i=0
    for mon in "$@"; do
        desktops=""
        d=$((i + 1))
        while [ "$d" -le 10 ]; do
            desktops="$desktops $d"
            d=$((d + n))
        done
        bspc monitor "$mon" -d $desktops
        i=$((i + 1))
    done
fi

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --set-zoom-fill "$HOME/.backgrounds/wow-horde.jpg" &

# Dex
dex -a -s "/etc/xdg/autostart/:$HOME/.config/autostart/" &

# Picom
picom -b &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &
