#! /bin/sh

# Set configuration
bspc config border_width              1
bspc config window_gap                2
bspc config split_ratio            0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer  true

# Border
bspc config focused_border_color "#8f7c56"
bspc config normal_border_color  "#073642"
bspc config active_border_color  "#073642"

# Assign application to workspaces
bspc rule -a keepassxc desktop='III'

#################################################################################
#                                 Autostart                                     #
#################################################################################

# Start sxhkd for keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Assign workspaces to displays
bspc monitor DisplayPort-0 -d I II III IV V
bspc monitor DisplayPort-2 -d VI VII VIII IX X

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --set-zoom-fill ~/.backgrounds/wow-horde.png &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# Picom
picom -CGb &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &
