[window]
opacity = 0.97

[font]
size = 9.0
normal.family = "FiraCode Nerd Font Mono"
bold.family = "FiraCode Nerd Font Mono"
italic.family = "FiraCode Nerd Font Mono"
bold_italic.family = "FiraCode Nerd Font Mono"

[colors]
primary.foreground = "#ffffff"
normal.white = "#eaeaea"
bright.white = "#ffffff"