#!/usr/bin/env bash

# Application: Git-Sync
# Description: Synchronize all local branches by fetching remotes and perform fast-forwarding
# Uage: git sync

GREEN=32
YELLOW=33

progress_bar() {
    length=$1
    basecolor=$2
    barcolor=$3
    value=$4
    maxvalue=$5

    percent=$((value * 100 / maxvalue))
    bars=$((percent * length / 100))

    LINE="\r\e[0;33m > Progress \e[0m"
    LINE="$LINE\e[0;${basecolor}m[\e[0m"
    for bar in $(seq "$length"); do
        if [ "$bar" -gt "$bars" ]; then
            LINE="$LINE "
        else
            LINE="$LINE\e[0;${barcolor}m#\e[0m"
        fi
    done
    LINE="$LINE\e[0;${basecolor}m]\e[0m"
    LINE="$LINE\e[0;33m \e[0m"
    echo -en "$LINE"
}

curbranch=$(git rev-parse --abbrev-ref HEAD)

git fetch --all --prune &>/dev/null

count=1
maxcount=0
for branch in $(git for-each-ref refs/heads --format="%(refname:short)"); do
    maxcount=$((maxcount + 1))
done

whitespace="                                 "

for branch in $(git for-each-ref refs/heads --format="%(refname:short)"); do
    progress_bar 20 $YELLOW $GREEN $count $maxcount

    # Skip branches without an upstream
    if git rev-parse --verify --quiet "$branch@{u}" >/dev/null; then
        upstream=$(git rev-parse --abbrev-ref "$branch@{u}")
        if [ "$branch" = "$curbranch" ]; then
            b1="$(git log -n 1 --pretty=format:"%H" "$branch" 2>/dev/null)"
            b2="$(git log -n 1 --pretty=format:"%H" "$branch@{u}" 2>/dev/null)"
            if [ -n "$b1" ] && [ -n "$b2" ] && [ "$b1" != "$b2" ]; then
                echo -en "\e[0;33m: Fast forwarding '$branch' ... \e[0m"
                if git merge --ff-only "$branch@{u}" &>/dev/null; then
                    echo -en "\r\e[0;33m > Fast forwarding '$branch' ... \e[0m"
                    echo -e "\e[0;32msuccess\e[0m$whitespace"
                else
                    echo -en "\r\e[0;33m > Fast forwarding '$branch' ... \e[0m"
                    echo -e "\e[0;31mfailure\e[0m$whitespace"
                fi
            fi
        else
            b1="$(git log -n 1 --pretty=format:"%H" "$branch" 2>/dev/null)"
            b2="$(git log -n 1 --pretty=format:"%H" "$branch@{u}" 2>/dev/null)"
            b1t="$(git log -n 1 --pretty=format:"%at" "$branch" 2>/dev/null)"
            b2t="$(git log -n 1 --pretty=format:"%at" "$branch@{u}" 2>/dev/null)"
            if [ -n "$b1" ] && [ -n "$b2" ] && [ "$b1" != "$b2" ]; then
                echo -en "\e[0;33m: Fast forwarding '$branch' ... \e[0m"
                if [ "$b1t" -lt "$b2t" ]; then
                    if git fetch . "$upstream:$branch" &>/dev/null; then
                        echo -en "\r\e[0;33m > Fast forwarding '$branch' ... \e[0m"
                        echo -e "\e[0;32msuccess\e[0m$whitespace"
                    else
                        echo -en "\r\e[0;33m > Fast forwarding '$branch' ... \e[0m"
                        echo -e "\e[0;31mfailure\e[0m$whitespace"
                    fi
                else
                    echo -en "\r\e[0;33m > Fast forwarding '$branch' ... \e[0m"
                    echo -e "\e[0;34mskipped\e[0m$whitespace"
                fi
            fi
        fi
    fi
    count=$((count + 1))
done
echo ""
