#!/bin/env bash

COMMIT_MSG_HOOK_CHECK_TAG='#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

OUTPUT_FILE="$1"

if [ -z "$OUTPUT_FILE" ]; then
    echo -e "\e[31mERROR: Missing output file.\e[0m"
    exit 1
else
    REGEX="([A-Z]+-[0-9]+)"
    BRANCH="$(git branch --show-current)"

    if [[ $BRANCH =~ $REGEX ]]; then
        HEAD="$(head -1 $OUTPUT_FILE)"
        echo "$HEAD" | grep -q "\[${BASH_REMATCH[1]}\]"
        if [ $? -ne 0 ]; then
            echo -e "\e[31mERROR: Commit aborted. Tag is missing in commit msg.\e[0m"
            exit 1
        fi

        REGEX="^[[:space:]]*\[${BASH_REMATCH[1]}\][[:space:]]*$"
        if [[ $HEAD =~ $REGEX ]]; then
            echo -e "\e[31mERROR: Commit aborted. No commit message provided.\e[0m"
            exit 1
        fi
    fi
fi'

PRE_COMMIT_HOOK_FOR_CLANG_FORMAT='#!/usr/bin/env bash

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$script_dir/../"

if [ -z "$(which clang-format)" ]; then
    echo -e "\n\e[31m  ERROR: Commit aborted. Formatter clang-format is missing. Please install clang-format for style check.\e[0m\n"
    exit 1
fi

version=$(clang-format --version | cut -f4 -d' ' | cut -f1 -d'.')
if [ $version -lt 18 ]; then
    echo -e "\n\e[31m  ERROR: Commit aborted. Only clang-format v18+ is supported. Please update clang-format.\e[0m\n"
    exit 1
fi

files=()
for file in `git diff --cached --name-only --diff-filter=ACMRT | grep -E "\.(c|cpp|cxx|cc|h|hpp|hxx)$"`; do
    output="$(cmp -b <(git show :${file}) <(git show :${file} | clang-format --style=file:.clang-format --Werror))"
    if [ $? -ne 0 ]; then
        files+=("${file}")
    fi
done

if [ -n "${files}" ]; then
    echo -e "\n  \e[33mAffected files:\e[0m\n"
    for file in ${files[@]}; do
        printf "    - %s\n\n" "${files[@]}"

        lnum=1
        while IFS= read -r line; do
            if [ $lnum -lt 3 ]; then
                echo -e "          | \e[01;97m$line\e[0m"
            elif [ $lnum -eq 3 ]; then
                echo -e "          | \e[36m$line\e[0m"
            elif [[ $line == +* ]]; then
                echo -e "          | \e[32m$line\e[0m"
            elif [[ $line == -* ]]; then
                echo -e "          | \e[31m$line\e[0m"
            else
                echo -e "          | $line"
            fi
            lnum=$((lnum+1))
        done < <(diff --color -u <(git show :${file}) <(git show :${file} | clang-format --style=file:.clang-format --Werror))
        echo
    done
    echo -e "\e[31m  ERROR: Commit aborted. Changes do not match with code style. Run clang-format first.\e[0m\n"
    exit 1
fi'

PREPARE_COMMIT_MSG_JIRA_TAG='#!/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

COMMIT_MSG="$1"

if [ -z "$COMMIT_MSG" ]; then
    echo -e "\e[31mERROR: Commit aborted. Missing argument in prepare-commit-msg.\e[0m"
    exit 1
else
    if [ ! -z "$(cat $COMMIT_MSG)" ]; then
        exit 0
    fi

    REGEX="([A-Z]+-[0-9]+)"
    BRANCH="$(/usr/bin/git branch --show-current)"

    if [[ $BRANCH =~ $REGEX ]]; then
        echo "[${BASH_REMATCH[1]}] " > "$COMMIT_MSG"
    fi
fi'

root_dir() {
    ROOT_DIR="$(pwd)"
    while true; do
        if [ -f "${ROOT_DIR}/.git" ]; then
            ROOT_DIR="$(cat "${ROOT_DIR}/.git" | grep gitdir | cut -f2 -d' ')"
        elif [ -d "${ROOT_DIR}/.git" ]; then
            echo $(realpath "${ROOT_DIR}")
            break
        else
            ROOT_DIR="${ROOT_DIR}/.."
        fi
    done
}

ROOT_DIR=$(root_dir)

if [ ! -d "${ROOT_DIR}/.git-hooks" ]; then
    mkdir -p "${ROOT_DIR}/.git-hooks"
fi

GIT_DIR=$(realpath "${ROOT_DIR}/.git")
GIT_HOOK_DIR=$(realpath "${ROOT_DIR}/.git-hooks")

HOOK_NAMES=(
    "applypatch-msg"
    "commit-msg"
    "post-applypatch"
    "post-commit"
    "post-merge"
    "post-receive"
    "post-update"
    "post-checkout"
    "prepare-commit-msg"
    "pre-applypatch"
    "pre-auto-gc"
    "pre-commit"
    "pre-merge-commit"
    "pre-push"
    "pre-rebase"
    "pre-receive"
    "prepare-commit"
    "push-to-checkout"
    "update"
)

cd "${ROOT_DIR}"

echo ""
if [ -z "$1" ] || [ "$1" == "install" ]; then
    echo -e "  \e[33mInstall git hooks\e[0m\n"

    echo '#!/bin/env bash

    if [ -x $0.local ]; then
        $0.local "$@" || exit $?
    fi
    
    HOOK="$(dirname $0)/../../.git-hooks/$(basename $0)"
    if [ -x "$HOOK" ]; then
        $HOOK "$@" || exit $?
    fi

    for f in ${GIT_HOOK_DIR}/*; do
        chmod +x $f
    done' > "${GIT_HOOK_DIR}/hooks-wrapper"
    
    chmod +x "${GIT_HOOK_DIR}/hooks-wrapper"

    echo -ne "  [\e[33m?\e[0m] Install PREPARE_COMMIT hook for Jira tags? [Y/n] " 1>&2
    read value
    if [ -z $value ] || [ "$value" == "y" ] || [ "$value" == "Y"]; then        
        (echo "$PREPARE_COMMIT_MSG_JIRA_TAG" > "${GIT_HOOK_DIR}/prepare-commit-msg" && chmod +x "${GIT_HOOK_DIR}/prepare-commit-msg" && echo "\e[32minstalled\e[0m")  || echo "\e[31mfailed\e[0m"
    fi

    echo -ne "  [\e[33m?\e[0m] Install PRE_COMMIT hook for clang-format? [Y/n] " 1>&2
    read value
    if [ -z $value ] || [ "$value" == "y" ] || [ "$value" == "Y"]; then
        (echo "$PRE_COMMIT_HOOK_FOR_CLANG_FORMAT" > "${GIT_HOOK_DIR}/pre-commit" && chmod +x "${GIT_HOOK_DIR}/pre-commit" && echo "\e[32minstalled\e[0m")  || echo "\e[31mfailed\e[0m"
    fi

    echo -ne "  [\e[33m?\e[0m] Install COMMIT_MSG hook for Jira tag check? [Y/n] " 1>&2
    read value
    if [ -z $value ] || [ "$value" == "y" ] || [ "$value" == "Y"]; then
        echo -n "    commit-msg ... "
        (echo "$COMMIT_MSG_HOOK_CHECK_TAG" > "${GIT_HOOK_DIR}/commit-msg" && chmod +x "${GIT_HOOK_DIR}/commit-msg" && echo "\e[32minstalled\e[0m")  || echo "\e[31mfailed\e[0m"
    fi

    HOOK_DIR="${GIT_DIR}/hooks"
    cd "${HOOK_DIR}"

    for hook in ${HOOK_NAMES[@]}; do
        echo -e "  \e[34m    Check hook $HOOK_DIR/$hook\e[0m"
        if [ ! -h $HOOK_DIR/$hook -a -x $HOOK_DIR/$hook ]; then
            echo -e "          Move existing hook $HOOK_DIR/$hook to $HOOK_DIR/$hook.local"
            mv $HOOK_DIR/$hook $HOOK_DIR/$hook.local
        fi
        echo -e "          Create symlink from $HOOK_DIR/$hook to ${GIT_HOOK_DIR}/hooks-wrapper"
        ln -s -f "../../.git-hooks/hooks-wrapper" $HOOK_DIR/$hook
        echo ""
    done
elif [ ! -z "$1" ] && [ "$1" == "uninstall" ]; then
    echo -e "  \e[33mUninstall git hooks\e[0m\n"

    if [ ! -d "${GIT_HOOK_DIR}" ]; then
        echo -e "  \e[34m   No hooks installed."
        exit 1
    fi

    HOOK_DIR="${GIT_DIR}/hooks"
    for hook in ${HOOK_NAMES[@]}; do
        echo -e "  \e[34m    Check hook $HOOK_DIR/$hook\e[0m"
        if [ -L  $HOOK_DIR/$hook ] && [ "$(realpath $HOOK_DIR/$hook)" == "$(realpath "$ROOT_DIR/.git-hooks/hooks-wrapper")" ]; then
            echo -e "          Remove symlink $HOOK_DIR/$hook"
            rm $HOOK_DIR/$hook

            if [ -e $HOOK_DIR/$hook.local ]; then
                echo -e "          Restore $HOOK_DIR/$hook.local as $HOOK_DIR/$hook"
                mv $HOOK_DIR/$hook.local $HOOK_DIR/$hook
            fi
        else
            echo -e "          Nothing to do for $HOOK_DIR/$hook"
        fi
        echo ""
    done
else
    echo -e "  \e[31mERROR: Invalid arguments specified '$@'\e[0m\n"
    exit 1
fi
